---
- name: install packages
  sudo: yes
  apt: name={{ item }} state=installed
  with_items:
    - build-essential
    - tree
    - unzip
    - git
    - tig
    - subversion
    - vim
    - tmux
    - openjdk-7-jdk
